/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tetris;

/**
 *
 * @author vm.alonsobarberan
 */
public class Scoreboard extends javax.swing.JPanel implements Incrementer {
    
    private int score;

    /**
     * Creates new form Scoreboard
     */
    public Scoreboard() {
        initComponents();
        score = 0;
        incrementScore(0);
    }
    
    public void incrementScore(int increment) {
        score += increment;
        jLabel1.setText("Score: " + score);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");
        add(jLabel1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void reset() {
        score = 0;
        incrementScore(0);
    }
}
